#!/bin/bash

NOTE_FILE="$HOME/Documents/notes/src/note-$(date +%Y-%m-%d).md"

if [ ! -f $NOTE_FILE ]; then
  echo "# Notes for $(date +%Y-%m-%d)" > $NOTE_FILE
fi

/opt/homebrew/bin/nvim -c "norm Go" \
  -c "norm Go## $(date +%H:%M)" \
  -c "norm G2o" \
  -c "norm zz" \
  -c "startinsert" $NOTE_FILE

